### ISSUE TITLE
Excess variable

### ISSUE THREAD

**Issue by pprettysimpple** [holounic/university#2]
https://github.com/holounic/university/blob/5e269e55ae2bc43ac121bc5f1ae40b2b7d7caae1/paradigms/semester-1/some-code/markup/MarkableBlock.java#L6

You store this variable in **every** instance of the **every** heir.
It would be better to do `void toMarkup(StringBuilder result, String border)` , so as not to store extra variables.
Just call this method in the heirs with the desired border.
(Some people got a ban from Korneev for this thing)

**Comment by artem** [comment]
можеш поруски написать нечево не понятно

**Comment by pprettysimpple** [comment]
> можеш поруски написать нечево не понятно

pashel nahui ;)

**Comment by holounic** [comment]
oh u english man

**Comment by artem** [comment]
mudroe decision
