### ISSUE TITLE
Че? Каво?

### ISSUE THREAD

**Issue by pprettysimpple** [holounic/university#3]
https://github.com/holounic/university/blob/4efe2811509cbb0932b070208629cccc25319440/paradigms/semester-1/some-code/markup/MarkupBlock.java#L15

Во-первых почему нельзя было написать `this.textField.get(i).toMarkdown(builder)`?
Тогда можно просто совсем стереть `String toMarkdown()`.

Во-вторых зачем делать `textField.get(i)`?
Тебе могут подсунуть `LinkedList` и проигрыш, потому что будет работать за квадрат. Лучше написать `foreach`, который гарантированно работает за линию при любой реализации интерфейста `List`.

За первый пункт скорее всего минус, а вот за второй БанБанБан.

**Comment by holounic** [comment]
справедливо
